package privateapp.mintplayer;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.media.MediaMetadataRetriever;import android.net.Uri;import android.os.*;import android.provider.*;import android.text.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;import java.util.concurrent.*;
public class MainActivity extends Activity {
 final int BG=0xff101416,CARD=0xff1c2428,INK=0xffeff5f2,MINT=0xff6ee7c4,MUTED=0xff9baaa5;
 ArrayList<Track> library=new ArrayList<>(),shown=new ArrayList<>();Set<String> favorites=new HashSet<>();JSONObject playlists=new JSONObject();String filter="",tab="전체",sort="제목";PlayerService svc;boolean bound=false,drag=false,active=false;int revision=0;
 LinearLayout root,list;TextView title,subtitle,time,mode,status;Button play,fav;SeekBar seek;SpectrumView spectrum;Handler handler=new Handler();ExecutorService worker=Executors.newSingleThreadExecutor();
 final ServiceConnection connection=new ServiceConnection(){public void onServiceConnected(ComponentName n,IBinder b){svc=((PlayerService.LocalBinder)b).get();}public void onServiceDisconnected(ComponentName n){svc=null;}};
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);load();build();bound=bindService(new Intent(this,PlayerService.class),connection,BIND_AUTO_CREATE);}
 int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} void message(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 GradientDrawable box(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(dp(4),dp(6),dp(4),dp(6));return t;}
 Button button(String s,Runnable action){Button b=new Button(this);b.setText(s);b.setTextSize(12);b.setTextColor(INK);b.setAllCaps(false);b.setBackground(box(CARD,14));b.setOnClickListener(v->action.run());return b;}
 LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}
 void add(LinearLayout row,View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(45),1);p.setMargins(dp(3),dp(3),dp(3),dp(3));row.addView(v,p);}
 void build(){root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(BG);root.setPadding(dp(16),dp(10),dp(16),dp(6));setContentView(root);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(dp(16),dp(8)+i.getSystemWindowInsetTop(),dp(16),dp(6)+i.getSystemWindowInsetBottom());return i;});root.requestApplyInsets();
 TextView brand=text("MINT / LOCAL AUDIO",13,MINT);brand.setLetterSpacing(.16f);root.addView(brand);
 TextView heading=text("나만의 음악 보관함",24,INK);heading.setTypeface(null,Typeface.BOLD);root.addView(heading);
 LinearLayout tools=row();add(tools,button("기기 검색",()->scanPermission()));add(tools,button("파일 가져오기",()->pick()));add(tools,button("정렬 · "+sort,()->new AlertDialog.Builder(this).setTitle("정렬 기준").setItems(new String[]{"제목","아티스트","앨범"},(d,w)->{sort=new String[]{"제목","아티스트","앨범"}[w];((Button)tools.getChildAt(2)).setText("정렬 · "+sort);render();}).show()));root.addView(tools);
 EditText search=new EditText(this);search.setSingleLine();search.setTextColor(INK);search.setTextSize(14);search.setHintTextColor(MUTED);search.setHint("제목, 아티스트, 앨범 검색");search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){filter=s.toString().toLowerCase(Locale.ROOT);render();}public void afterTextChanged(Editable e){}});root.addView(search);
 LinearLayout tabs=row();add(tabs,button("전체",()->{tab="전체";render();}));add(tabs,button("♥ 즐겨찾기",()->{tab="즐겨찾기";render();}));add(tabs,button("플레이리스트",()->choosePlaylist()));root.addView(tabs);
 status=text("",12,MUTED);root.addView(status);ScrollView scroll=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(1);scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
 LinearLayout player=new LinearLayout(this);player.setOrientation(1);player.setPadding(dp(12),dp(6),dp(12),dp(8));player.setBackground(box(CARD,24));root.addView(player);
 title=text("음악을 선택하세요",20,INK);title.setMaxLines(1);title.setEllipsize(TextUtils.TruncateAt.END);title.setTypeface(null,Typeface.BOLD);subtitle=text("OFFLINE · PRIVATE · YOURS",12,MUTED);subtitle.setMaxLines(1);player.addView(title);player.addView(subtitle);
 spectrum=new SpectrumView(this);player.addView(spectrum,new LinearLayout.LayoutParams(-1,dp(54)));spectrum.setOnClickListener(v->visualPermission());
 seek=new SeekBar(this);seek.setProgressTintList(android.content.res.ColorStateList.valueOf(MINT));seek.setThumbTintList(android.content.res.ColorStateList.valueOf(MINT));seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean u){}public void onStartTrackingTouch(SeekBar s){drag=true;}public void onStopTrackingTouch(SeekBar s){if(svc!=null)svc.seek(s.getProgress());drag=false;}});player.addView(seek);time=text("0:00  /  0:00",11,MUTED);player.addView(time);
 LinearLayout controls=row();add(controls,button("⏮",()->{if(svc!=null)svc.previous();}));play=button("▶",()->{if(svc!=null)svc.toggle();});play.setTextColor(BG);play.setBackground(box(MINT,18));add(controls,play);add(controls,button("⏭",()->{if(svc!=null)svc.next(true);}));fav=button("♡",()->{if(svc!=null&&svc.current()!=null)favorite(svc.current());});add(controls,fav);player.addView(controls);
 mode=text("셔플 끔 · 반복 끔",12,MUTED);player.addView(mode);mode.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("재생 설정").setItems(new String[]{"셔플 켜기 / 끄기","반복: 끔 → 전체 → 한 곡","비주얼라이저 활성화"},(d,w)->{if(svc==null)return;if(w==0)svc.shuffle=!svc.shuffle;if(w==1)svc.repeat=(svc.repeat+1)%3;if(w==2)visualPermission();}).show());render();}
 void load(){android.content.SharedPreferences p=getSharedPreferences("data",0);favorites=new HashSet<>(p.getStringSet("favorites",new HashSet<>()));try{JSONArray a=new JSONArray(p.getString("library","[]"));for(int i=0;i<a.length();i++)library.add(Track.read(a.getJSONObject(i)));playlists=new JSONObject(p.getString("playlists","{}"));}catch(Exception e){message("저장된 목록을 읽지 못했습니다.");}}
 void save(){JSONArray a=new JSONArray();for(Track t:library)a.put(t.json());getSharedPreferences("data",0).edit().putString("library",a.toString()).putStringSet("favorites",favorites).putString("playlists",playlists.toString()).apply();}
 Track find(String u){for(Track t:library)if(t.uri.equals(u))return t;return null;}
 void merge(ArrayList<Track> tracks){for(Track t:tracks){Track old=find(t.uri);if(old==null)library.add(t);else{old.title=t.title;old.artist=t.artist;old.album=t.album;}}save();render();}
 void render(){if(list==null)return;shown.clear();if(!tab.equals("전체")&&!tab.equals("즐겨찾기")){JSONArray a=playlists.optJSONArray(tab);if(a!=null)for(int i=0;i<a.length();i++){Track t=find(a.optString(i));if(t!=null)shown.add(t);}}else{for(Track t:library)if(!tab.equals("즐겨찾기")||favorites.contains(t.uri))shown.add(t);shown.sort((a,b)->(sort.equals("앨범")?a.album:sort.equals("아티스트")?a.artist:a.title).compareToIgnoreCase(sort.equals("앨범")?b.album:sort.equals("아티스트")?b.artist:b.title));}
 shown.removeIf(t->!(t.title+" "+t.artist+" "+t.album).toLowerCase(Locale.ROOT).contains(filter));list.removeAllViews();status.setText(tab+"  ·  "+shown.size()+"곡  /  길게 눌러 관리");
 if(shown.isEmpty()){TextView empty=text("아직 음악이 없나요?
‘기기 검색’ 또는 ‘파일 가져오기’를 눌러 주세요.

음악 파일은 이동하거나 삭제하지 않습니다.",14,MUTED);empty.setPadding(dp(12),dp(28),dp(12),dp(28));list.addView(empty);}
 for(Track t:shown){LinearLayout item=new LinearLayout(this);item.setOrientation(1);item.setPadding(dp(12),dp(6),dp(12),dp(6));item.setBackground(box(CARD,14));TextView name=text((favorites.contains(t.uri)?"♥  ":"♪  ")+t.title,15,INK);name.setMaxLines(1);name.setEllipsize(TextUtils.TruncateAt.END);item.addView(name);TextView meta=text(t.artist+" · "+t.album,11,MUTED);meta.setMaxLines(1);item.addView(meta);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(4),0,dp(4));list.addView(item,lp);item.setOnClickListener(v->{if(svc!=null){startService(new Intent(this,PlayerService.class));svc.start(new ArrayList<>(shown),shown.indexOf(t));}});item.setOnLongClickListener(v->{trackMenu(t);return true;});}}
 void favorite(Track t){if(!favorites.remove(t.uri))favorites.add(t.uri);save();render();}
 boolean custom(){return !tab.equals("전체")&&!tab.equals("즐겨찾기");}
 void trackMenu(Track t){String[] opts=custom()?new String[]{"즐겨찾기 전환","다른 플레이리스트에 추가","위로 이동","아래로 이동","이 목록에서 제거"}:new String[]{"즐겨찾기 전환","플레이리스트에 추가","보관함에서 제거 (원본 유지)"};new AlertDialog.Builder(this).setTitle(t.title).setItems(opts,(d,w)->{if(w==0)favorite(t);else if(w==1)addToPlaylist(t);else if(custom()){JSONArray a=playlists.optJSONArray(tab);ArrayList<String> ids=new ArrayList<>();for(int i=0;i<a.length();i++)ids.add(a.optString(i));int at=ids.indexOf(t.uri);if(w==4)ids.remove(t.uri);else if(at>=0){int to=at+(w==2?-1:1);if(to>=0&&to<ids.size())Collections.swap(ids,at,to);}try{playlists.put(tab,new JSONArray(ids));}catch(Exception e){}save();render();}else new AlertDialog.Builder(this).setMessage("보관함에서만 제거할까요? 원본 파일과 현재 재생 대기열은 유지됩니다.").setPositiveButton("제거",(x,y)->{library.remove(t);save();render();}).setNegativeButton("취소",null).show();}).show();}
 ArrayList<String> names(){ArrayList<String> a=new ArrayList<>();playlists.keys().forEachRemaining(a::add);Collections.sort(a);return a;}
 void nameDialog(String old){EditText input=new EditText(this);input.setSingleLine();input.setText(old==null?"":old);new AlertDialog.Builder(this).setTitle(old==null?"새 플레이리스트":"이름 변경").setView(input).setPositiveButton("저장",(d,w)->{String n=input.getText().toString().trim();if(n.isEmpty()||n.equals("전체")||n.equals("즐겨찾기")||playlists.has(n)){message("중복되지 않는 다른 이름을 입력하세요.");return;}try{playlists.put(n,old==null?new JSONArray():playlists.getJSONArray(old));if(old!=null)playlists.remove(old);tab=n;save();render();}catch(Exception e){}}).setNegativeButton("취소",null).show();}
 void choosePlaylist(){ArrayList<String> a=names();a.add(0,"＋ 새 플레이리스트");new AlertDialog.Builder(this).setTitle("플레이리스트").setItems(a.toArray(new String[0]),(d,w)->{if(w==0){nameDialog(null);return;}tab=a.get(w);render();new AlertDialog.Builder(this).setTitle(tab).setItems(new String[]{"목록 보기","이름 변경","목록 삭제"},(x,y)->{if(y==1)nameDialog(tab);if(y==2)new AlertDialog.Builder(this).setMessage("플레이리스트만 삭제할까요? 원본 파일은 유지됩니다.").setPositiveButton("삭제",(q,r)->{playlists.remove(tab);tab="전체";save();render();}).setNegativeButton("취소",null).show();}).show();}).show();}
 void addToPlaylist(Track t){ArrayList<String> a=names();if(a.isEmpty()){message("먼저 플레이리스트를 만든 다음 곡을 추가하세요.");nameDialog(null);return;}new AlertDialog.Builder(this).setTitle("추가할 목록").setItems(a.toArray(new String[0]),(d,w)->{JSONArray ids=playlists.optJSONArray(a.get(w));for(int i=0;i<ids.length();i++)if(ids.optString(i).equals(t.uri)){message("이미 추가된 곡입니다.");return;}ids.put(t.uri);save();render();message("추가했습니다.");}).show();}
 void scanPermission(){String p=Build.VERSION.SDK_INT>=33?Manifest.permission.READ_MEDIA_AUDIO:Manifest.permission.READ_EXTERNAL_STORAGE;if(checkSelfPermission(p)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{p},10);else scan();}
 void visualPermission(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED){message("재생 중인 음악에 맞춰 시각 효과가 표시됩니다.");return;}new AlertDialog.Builder(this).setTitle("비주얼라이저 권한").setMessage("Android의 오디오 시각화 API는 ‘마이크’ 권한을 요구합니다. 이 앱은 마이크 입력을 녹음하거나 저장하지 않고 재생 오디오만 시각화합니다. 거절해도 음악 재생은 가능합니다.").setPositiveButton("허용 요청",(d,w)->requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},11)).setNegativeButton("나중에",null).show();}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==10){if(g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)scan();else message("권한 없이도 파일 가져오기를 사용할 수 있습니다.");}}
 void scan(){status.setText("기기의 오디오 목록 검색 중…");worker.execute(()->{ArrayList<Track> out=new ArrayList<>();String err=null;try(Cursor c=getContentResolver().query(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,new String[]{"_id","title","artist","album"},null,null,null)){if(c!=null)while(c.moveToNext())out.add(new Track(ContentUris.withAppendedId(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,c.getLong(0)).toString(),safe(c.getString(1),"이름 없는 음악"),safe(c.getString(2),"알 수 없는 아티스트"),safe(c.getString(3),"앨범 없음")));}catch(Exception e){err="검색 실패: 음악 접근 권한을 확인하세요.";}final String failure=err;runOnUiThread(()->{if(isDestroyed())return;merge(out);message(failure==null?out.size()+"곡 확인. 검색되지 않으면 파일 가져오기를 사용하세요.":failure);});});}
 String safe(String s,String fallback){return s==null||s.isEmpty()||s.equals("<unknown>")?fallback:s;}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("audio/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,20);}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r!=20||result!=RESULT_OK||data==null)return;ArrayList<Uri> uris=new ArrayList<>();if(data.getClipData()!=null){for(int i=0;i<data.getClipData().getItemCount();i++)uris.add(data.getClipData().getItemAt(i).getUri());}else if(data.getData()!=null)uris.add(data.getData());for(Uri u:uris)try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){message("일부 파일 제공자는 영구 접근을 지원하지 않습니다.");}status.setText("파일 정보를 읽는 중…");worker.execute(()->{ArrayList<Track> out=new ArrayList<>();for(Uri u:uris){String name="음악 파일",artist="알 수 없는 아티스트",album="앨범 없음";try(Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int col=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(col>=0)name=c.getString(col);}}catch(Exception e){}MediaMetadataRetriever m=new MediaMetadataRetriever();try{m.setDataSource(this,u);name=safe(m.extractMetadata(7),name);artist=safe(m.extractMetadata(2),artist);album=safe(m.extractMetadata(1),album);}catch(Exception e){}finally{try{m.release();}catch(Exception e){}}out.add(new Track(u.toString(),name,artist,album));}runOnUiThread(()->{if(!isDestroyed())merge(out);});});}
 String clock(int ms){return String.format(Locale.ROOT,"%d:%02d",ms/60000,(ms/1000)%60);}
 String lastError="";final Runnable tick=new Runnable(){public void run(){if(!active)return;if(svc!=null){Track t=svc.current();if(t!=null){title.setText(t.title);subtitle.setText(t.artist+" · "+t.album);fav.setText(favorites.contains(t.uri)?"♥":"♡");}play.setText(svc.playing()?"Ⅱ":"▶");if(!drag){seek.setMax(Math.max(1,svc.duration()));seek.setProgress(svc.position());}time.setText(clock(svc.position())+"  /  "+clock(svc.duration()));mode.setText("셔플 "+(svc.shuffle?"켬":"끔")+" · 반복 "+new String[]{"끔","전체","한 곡"}[svc.repeat]+" · 시각화 설정");if(!svc.error.isEmpty()&&!svc.error.equals(lastError))message(svc.error);lastError=svc.error;if(svc.playing()&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)spectrum.attach(svc.player.getAudioSessionId());else spectrum.release();}handler.postDelayed(this,350);}};
 protected void onResume(){super.onResume();active=true;handler.post(tick);if(Build.VERSION.SDK_INT>=33&&!getSharedPreferences("data",0).getBoolean("notificationAsked",false)){getSharedPreferences("data",0).edit().putBoolean("notificationAsked",true).apply();requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},12);}}
 protected void onPause(){active=false;handler.removeCallbacks(tick);spectrum.release();super.onPause();}
 protected void onDestroy(){if(bound)unbindService(connection);worker.shutdown();super.onDestroy();}
}
